version: '3'

services:
  web:
    build: .
    command: python ethnic_eats/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
  #   environment:
  #     - REDIS_HOST=redis
  
  # redis:
  #   image: redis:7
  #   ports:
  #     - "6379:6379"
