# Generated by Django 5.0 on 2024-05-26 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatrooms', '0002_chatroom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='room_name',
            new_name='room',
        ),
    ]
