# Generated by Django 5.0 on 2024-05-26 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatrooms', '0003_rename_room_name_chatmessage_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='name',
            new_name='room',
        ),
    ]
