# Generated by Django 5.0 on 2024-05-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatrooms', '0004_rename_name_chatroom_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='user',
            field=models.TextField(default='anonymous'),
        ),
    ]
