# Generated by Django 5.0 on 2024-04-01 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationDetail',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('cuisine_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=70, unique=True)),
                ('description', models.CharField(max_length=400)),
                ('contact', models.CharField(max_length=500, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
                ('time_open', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CuisinePictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine_picture', models.FileField(upload_to='cuisines/')),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='app.cuisine')),
            ],
        ),
        migrations.CreateModel(
            name='MealModel',
            fields=[
                ('meal_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('meal_name', models.CharField(max_length=50, unique=True)),
                ('price', models.IntegerField()),
                ('category', models.CharField(max_length=50)),
                ('cuisine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cuisine')),
            ],
        ),
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('post_description', models.CharField(max_length=2000)),
                ('post_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_pic', models.FileField(upload_to='posts/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='app.userpost')),
            ],
        ),
        migrations.CreateModel(
            name='UserReviews',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('review', models.CharField(max_length=300)),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cuisine')),
            ],
        ),
    ]
