# Generated by Django 5.0 on 2024-04-02 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=20)),
                ('review', models.CharField(max_length=300)),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cuisine')),
            ],
        ),
        migrations.DeleteModel(
            name='UserReviews',
        ),
    ]
