# Generated by Django 5.0.6 on 2024-06-17 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ratings',
            unique_together=set(),
        ),
    ]
