# Generated by Django 5.0 on 2024-04-02 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_reviews_delete_userreviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealmodel',
            old_name='cuisine_id',
            new_name='cuisine',
        ),
    ]
