# Generated by Django 5.0.6 on 2024-06-05 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_inquires'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuisine',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
    ]
