# Generated by Django 5.0.6 on 2024-07-05 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_ratings_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribeNewLetter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
