# Generated by Django 5.0.6 on 2024-06-05 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cuisine_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationdetail',
            name='cuisine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.cuisine'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mealmodel',
            name='price',
            field=models.FloatField(),
        ),
    ]
