# Generated by Django 5.0.6 on 2024-07-07 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_subscribenewletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationdetail',
            name='cuisine',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.cuisine'),
        ),
    ]
