# Generated by Django 5.0 on 2024-05-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_communityforummodel_reservationmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationmodel',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
