# Generated by Django 5.0.6 on 2024-06-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_locationdetail_cuisine_alter_mealmodel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealmodel',
            name='meal_pic',
            field=models.FileField(blank=True, null=True, upload_to='meals/'),
        ),
    ]
