# Generated by Django 4.2.13 on 2024-07-13 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_locationdetail_cuisine'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealModelIntense',
            fields=[
                ('meal_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('meal_name', models.CharField(max_length=50, unique=True)),
                ('price', models.FloatField()),
                ('category', models.CharField(max_length=50)),
                ('meal_pic', models.FileField(blank=True, null=True, upload_to='meals/')),
                ('ingredients', models.CharField(max_length=200)),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cuisine')),
            ],
        ),
    ]
