# Generated by Django 5.0 on 2024-05-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_reservationmodel_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuisine',
            name='contact',
            field=models.CharField(max_length=500),
        ),
    ]
