# Generated by Django 4.2.13 on 2024-07-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_mealmodelintense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealmodelintense',
            name='ingredients',
            field=models.CharField(max_length=500),
        ),
    ]
