# Generated by Django 5.0.6 on 2024-06-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_mealmodel_meal_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuisine',
            name='cuisine_pic',
            field=models.FileField(blank=True, null=True, upload_to='cuisines/'),
        ),
        migrations.DeleteModel(
            name='CuisinePictures',
        ),
    ]
