# Generated by Django 4.2.13 on 2024-07-13 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_mealmodelintense_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='meal_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mealmodelintense'),
        ),
    ]
