# Generated by Django 5.0 on 2024-05-26 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_communityforummodel_members'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommunityForumModel',
        ),
    ]
